FROM eclipse-temurin:21.0.3_9-jdk-alpine@sha256:ebfc28d35b192c55509e3c7cc597d91136528f1a9d3261965b44663af9eb4b4b AS builder
FROM ghcr.io/graalvm/jdk-community:21@sha256:57e5c4cf8536dac4346611691c31ea4828f3ff7bbb0d3695902b234f69ed99b5 AS builder
FROM ghcr.io/graalvm/graalvm-community:21@sha256:6e46c711c90bdbc24e23ccdb6e3fba837d660e68dd4ffeb87abbd3d08e115653 AS builder
FROM ghcr.io/graalvm/native-image-community:22@sha256:bed26bb73a090382d35cb5e8b6efaff76dcb1c974c3de0e690957028aceb7d87 AS builder
FROM ghcr.io/graalvm/native-image-community:22-muslib@sha256:d09155d8f19e17b72d240d336d010ee6f48b87ec2a9fc90595a17cc8257fe8ae AS builder

WORKDIR /opt/demo

COPY .mvn .mvn
COPY docker docker
COPY script script
COPY src src
COPY mvnw .
COPY pom.xml .

RUN microdnf update -y && \
    microdnf install -y maven gcc glibc-devel zlib-devel libstdc++-devel gcc-c++ && \
    microdnf clean all

RUN ./mvnw dependency:go-offline

# RUN ./mvnw clean install
RUN ./mvnw -Pnative native:compile -DskipTests -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dmaven.source.skip

# FROM eclipse-temurin:21.0.3_9-jre-alpine@sha256:23467b3e42617ca197f43f58bc5fb03ca4cb059d68acd49c67128bfded132d67
# FROM debian:stable-slim

# WORKDIR /opt/demo

# # Copy JAR from builder stage
# COPY --from=builder /opt/demo/target/*.jar /opt/demo/app.jar

# # Define the entrypoint
# ENTRYPOINT ["java", "-jar", "/opt/demo/app.jar"]
