version: "3.9"

services:
  database:
    image: postgres:16.2-alpine3.19@sha256:20baeb0510ac2612dab79f843309b37c08ad04adc5d75196f700d29f1da43a38
    environment:
      - POSTGRES_USER=mldemo
      - POSTGRES_PASSWORD=mldemo
    # volumes:
    #   - /var/mldemo/volumes/lib/postgresql/data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
