version: "3.9"

include:
  - ./docker-compose-database.yaml

services:
  api01: &api
    image: api01
    build:
      context: ../
      dockerfile: Dockerfile.native
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mldemo
      - SPRING_DATASOURCE_USERNAME=mldemo
      - SPRING_DATASOURCE_PASSWORD=mldemo
      - PORT=8080
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend
    depends_on:
      database:
        condition: service_healthy
